INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('1', ' Anguilla', '1', 'AI', ' XCD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('2', ' Antigua and Barbuda', '1', 'AG', ' XCD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('3', ' Argentina', '1', 'AR', ' ARS');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('4', ' Aruba', '1', 'AW', ' AWG');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('5', ' Bahamas', '1', 'BS', ' BSD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('6', ' Barbados', '1', 'BB', ' BBD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('7', ' Belize', '1', 'BZ', ' BZD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('8', ' Bermuda', '1', 'BM', ' BMD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('9', ' Bolivia', '1', 'BO', ' BOB');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('10', ' Bonaire', '1', 'BQ', ' USD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('11', ' Brazil', '1', 'BR', ' BRL');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('12', ' British Virgin Islands', '1', 'VG', ' USD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('13', ' Canada', '1', 'CA', ' CAD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('14', ' Cayman Islands', '1', 'KY', ' KYD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('15', ' Chile', '1', 'CL', ' CLF');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('16', ' Colombia', '1', 'CO', ' COP');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('17', ' Costa Rica', '1', 'CR', ' CRC');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('18', ' Cuba', '1', 'CU', ' CUP');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('19', ' Curaao', '1', 'CW', ' ANG');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('20', ' Dominica', '1', 'DM', ' XCD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('21', ' Dominican Republic', '1', 'DO', ' DOP');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('22', ' Ecuador', '1', 'EC', ' USD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('23', ' El Salvador', '1', 'SV', ' SVC');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('24', ' Falkland Islands', '1', 'FK', ' FKP');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('25', ' Grenada', '1', 'GD', ' XCD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('26', ' Guatemala', '1', 'GT', ' GTQ');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('27', ' Guyana', '1', 'GY', ' GYD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('28', ' Haiti', '1', 'HT', ' HTG');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('29', ' Honduras', '1', 'HN', ' HNL');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('30', ' Jamaica', '1', 'JM', ' JMD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('31', ' Mexico', '1', 'MX', ' MXN');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('32', ' Montserrat', '1', 'MS', ' XCD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('33', ' Nicaragua', '1', 'NI', ' NIO');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('34', ' Panama', '1', 'PA', ' PAB');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('35', ' Paraguay', '1', 'PY', ' PYG');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('36', ' Peru', '1', 'PE', ' PEN');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('37', ' Puerto Rico & United States Virgin Islands', '1', 'VI', ' USD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('38', ' Saint Kitts and Nevis', '1', 'KN', ' XCD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('39', ' Saint Lucia', '1', 'LC', ' XCD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('40', ' Saint Vincent and the Grenadines', '1', 'VC', ' XCD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('41', ' Suriname', '1', 'SR', ' SRD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('42', ' Trinidad and Tobago', '1', 'TT', ' TTD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('43', ' Turks and Caicos Islands', '1', 'TC', ' USD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('44', ' United States', '1', 'US', ' USD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('45', ' Uruguay', '1', 'UY', ' UYU');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('46', ' Venezuela', '1', 'VE', ' VEF');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('47', ' Australia', '3', 'AU', ' AUD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('48', ' New Zealand', '3', 'NZ', ' NZD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('49', ' Austria', '2', 'AT', ' EUR');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('50', ' Belgium', '2', 'BE', ' EUR');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('51', ' Bulgaria', '2', 'BG', ' BGN');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('52', ' Croatia', '2', 'HR', ' HRK');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('53', ' Cyprus', '2', 'CY', ' EUR');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('54', ' Czech Republic', '2', 'CZ', ' CZK');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('55', ' Denmark', '2', 'DK', ' DKK');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('56', ' Finland', '2', 'FI', ' EUR');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('57', ' France', '2', 'FR', ' EUR');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('58', ' Georgia', '2', 'GE', ' GEL');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('59', ' Germany', '2', 'DE', ' EUR');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('60', ' Greece', '2', 'GR', ' EUR');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('61', ' Greenland', '2', 'GL', ' DKK');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('62', ' Guernsey', '2', 'GG', ' GBP');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('63', ' Hungary', '2', 'HU', ' HUF');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('64', ' Iceland', '2', 'IS', ' ISK');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('65', ' Ireland', '2', 'IE', ' EUR');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('66', ' Isle of Man', '2', 'IM', ' GBP');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('67', ' Italy', '2', 'IT', ' EUR');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('68', ' Jersey', '2', 'JE', ' GBP');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('69', ' Netherlands', '2', 'NL', ' EUR');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('70', ' Norway', '2', 'NO', ' NOK');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('71', ' Poland', '2', 'PL', ' PLN');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('72', ' Portugal', '2', 'PT', ' EUR');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('73', ' Russia', '2', 'RU', ' RUB');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('74', ' Spain', '2', 'ES', ' EUR');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('75', ' Sweden', '2', 'SE', ' SEK');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('76', ' Switzerland', '2', 'CH', ' CHF');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('77', ' United Kingdom', '2', 'GB', ' GBP');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('78', ' Guadeloupe', '1', 'GP', ' EUR');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('79', ' Guam', '1', 'GU', ' USD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('80', ' Puerto Rico', '1', 'PR', ' USD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('81', ' China', '3', 'CN', ' CNY');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('82', ' Hong Kong', '3', 'HK', ' HKD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('83', ' India', '3', 'IN', ' INR');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('84', ' Indonesia', '3', 'ID', ' IDR');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('85', ' Japan', '3', 'JP', ' JPY');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('86', ' Korea', '3', 'KR', ' KRW');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('87', ' Lebanon', '2', 'LB', ' LBP');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('88', ' Malaysia', '3', 'MY', ' MYR');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('89', ' Philippines', '3', 'PI', ' PHP');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('90', ' Singapore', '3', 'SG', ' SGD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('91', ' South Africa', '3', 'ZA', ' ZAR');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('92', ' Taiwan', '3', 'TW', ' TWD');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('93', ' Thailand', '3', 'TH', ' THB');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('94', ' Turkey', '2', 'TR', ' TRY');
INSERT INTO `FaizTest`.`country` (`id`, `name`, `continent_id`, `alpha_2_code`, `currency_code`) VALUES ('95', ' United Arab Emirates', '3', 'AE', ' ARE');